### ISSUE TITLE
No results outputting

### ISSUE THREAD

**Issue by BirdLeaflol** [Techcatchers/PyLyrics-Extractor#5] opened 2020-06-15 15:34 UTC
Exact same problem as the guy below me
please fix I have to show off my final project for my computer science class tomorrow and it is very reliant on this.

**Comment by Techcatchers** [comment] 2020-06-15 16:11
Could you please elaborate your issue with the song name you're looking for?

**Comment by BirdLeaflol** [comment] 2020-06-15 16:20
It's happened on every song name that I've tried. Nothing I seem to try works. If you want an example of a song I tried, I used Africa by Toto for a lot of my testing.

**Comment by Techcatchers** [comment] 2020-06-15 20:12
Could you clone the repo and try to debug from your side? I am involved with other projects right now so I won't be able to pick this up right now. But if it's urgent, I can fix and provide a temporary solution for you once you let me know the exact error.

**Comment by Techcatchers** [comment] 2020-08-03 19:15
Please check now. The issue is now fixed and I have changed parser to improve performance and error rate should also go down as now if the scraping fails from one result URL, it looks for the other one until all top results are exhausted.

Please star the repository if you liked it :)

**Closed by Techcatchers** 2020-08-03 19:15 UTC
